use std::collections::HashSet;
use std::net::Ipv4Addr;
use std::path::PathBuf;

use tokio::sync::Mutex;

/// Shared, mutable state for one helper process lifetime.
pub(crate) struct HelperState {
    /// One-time secret the client must echo in its [`Handshake`]. Generated by
    /// the app and passed at spawn; the helper never logs it.
    ///
    /// [`Handshake`]: ferrisscope_core::globalfwd::protocol::Handshake
    pub(crate) token: String,
    /// System hosts file we manage a block in (`/etc/hosts`, or the Windows
    /// path; overridable in tests).
    pub(crate) hosts_path: PathBuf,
    /// Where the original hosts file is copied once, before our first edit.
    pub(crate) hosts_backup: PathBuf,
    /// Loopback aliases we've created and must tear down on exit. Empty on
    /// Linux (the whole `127.0.0.0/8` loops without aliases).
    pub(crate) aliases: Mutex<HashSet<Ipv4Addr>>,
}

impl HelperState {
    pub(crate) fn new(token: String, hosts_path: PathBuf, hosts_backup: PathBuf) -> Self {
        Self {
            token,
            hosts_path,
            hosts_backup,
            aliases: Mutex::new(HashSet::new()),
        }
    }
}
